### ISSUE TITLE
File Upload not working

### ISSUE THREAD

**Issue by itsmenayan** [RadouaneRoufid/angular#1]
When uploading file from angular it is trying to hit the backend api at port 4200. Thus not saving the file at the specified directory.

**Comment by RadouaneRoufid** [comment]
Actually, the file will be uploaded to localhost:4200/api/files. Since I'm using angular cli proxy, it will redirect the http request to localhost:8080 ([here is the configuration of the proxy](https://github.com/RadouaneRoufid/angular/blob/master/angular-springboot-file-upload/src/angular/proxy.conf.json))

You have to start the server with `npm start` or `ng serve --proxy-config proxy.conf.json --port 4200`

**Comment by itsmenayan** [comment]
I tried hitting directly localhost:8080/api/files after removing angular cli proxy, but not it is giving me CORS error. I have added @CrossOrigin(origins = "localhost:4200"), still doesn't make it work. Any suggestions?

**Comment by RadouaneRoufid** [comment]
The easier solution will be to use the angular cli proxy. Otherwise, try to set up a CorsFilter

```
@Bean
public CorsFilter corsFilter() {
	UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
	CorsConfiguration config = new CorsConfiguration();
	config.setAllowCredentials(true);
	config.addAllowedOrigin("http://localhost:4200");
	config.addAllowedHeader("*");
	config.addAllowedMethod("*");
	config.setMaxAge(600L);
	source.registerCorsConfiguration("/**", config);

	return new CorsFilter(source);
}
```

**Comment by itsmenayan** [comment]
Thanks :)
